steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$_PROJECT_ID/pinyin-conversion-service", "."]
    # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$_PROJECT_ID/pinyin-conversion-service"]
    # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "pinyin-conversion-service",
        "--image",
        "gcr.io/$_PROJECT_ID/pinyin-conversion-service",
        "--region",
        "us-central1",
      ]
images:
  - gcr.io/$_PROJECT_ID/pinyin-conversion-service
timeout: 660s
